version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    # Setting to 0 since I usually update repo from quartz/v4
    open-pull-requests-limit: 0
